### ISSUE TITLE
window control buttons are duplicated(bug)

### ISSUE THREAD

**Issue by cleuton4k** [poochie89/SnipDo-Extensions#14] opened 2022-11-01 04:09 UTC
When opening the app's settings window, the minimize, maximize and close buttons of other apps are duplicated, and they only restore to normal when I close and open the snipdo.
![SharedScreenshot](https://user-images.githubusercontent.com/90144967/199156796-9ecf0ec5-d71f-4efc-8eba-908241697238.jpg)

**Comment by poochie89** [comment] 2022-11-01 07:39
Hey, can you describe exactly what need to be done to replicate this bug, i tried several things but couldnt reproduce

**Comment by cleuton4k** [comment] 2022-11-02 01:31
it happens randomly, but it only happens when I open the snipdo settings or when the app is updated and the message with the changelog appears.

**Comment by Monster-DP** [comment] 2022-11-03 02:04
> 嘿，您能否准确描述复制此错误需要做什么，我尝试了几件事但无法重现

It must appear after I restart the computer

**Comment by poochie89** [comment] 2022-11-03 07:42
Ok, finally found out whats going on. Will be fixed in next update

**Comment by poochie89** [comment] 2022-11-20 18:00
Fixed

**Closed by poochie89** 2022-11-20 18:00 UTC
Labels: bug
