### ISSUE TITLE
Bar changes position when you have 2 different scaled monitors

### ISSUE THREAD

**Issue by lcp79** [poochie89/SnipDo-Extensions#13] opened 2022-10-20 23:42 UTC
Can you help me with this issue please

OK monitor 5120x1440 scaled 100%  monitor Principal
![20221020_183930](https://user-images.githubusercontent.com/115731470/197079116-e316febc-22ec-4342-8cbe-ee045a56ca5e.jpg)

Bad monitor  2560x1600  scaled 125% monitor secundary
![20221020_183910](https://user-images.githubusercontent.com/115731470/197079133-058b4d61-6fa7-4cfd-9992-5d8dca442881.jpg)

![image](https://user-images.githubusercontent.com/115731470/197078571-7fe2e276-e5e2-478b-a16f-83e1aec9e063.png)

![image](https://user-images.githubusercontent.com/115731470/197078617-1babfde3-7a74-4d20-831a-5546b4986a47.png)

**Comment by poochie89** [comment] 2022-10-21 10:34
Thanks for the bug report,
will check it out

**Comment by poochie89** [comment] 2022-10-26 12:37
I implemented a possible fix for this in 3.0.20

**Comment by lcp1979** [comment] 2022-10-26 22:55
Thank you, the issue is corrected

**Closed** 2022-10-27 06:39 UTC
